import { Project, TaskItem, CustomColumn, ProjectBaselineVersion } from '../types';
import { recalculateWbsCodes, rollupSummaryTasks } from './wbs';

export const initialBaselineVersionsErp: ProjectBaselineVersion[] = [
  {
    id: 'bl-erp-v1',
    projectId: 'proj-erp-cloud',
    versionNumber: 1,
    name: 'Baseline 1: Approved Initial Schedule & Resource Allocation',
    description: 'Initial project charter schedule baseline approved by Steering Committee on Sep 01.',
    createdAt: '2026-09-01T08:00:00Z',
    createdBy: 'Sarah Jenkins, PMP',
    tasks: [
      {
        id: 't-1',
        name: 'Phase 1: Project Initiation & Assessment',
        wbs: '1',
        startDate: '2026-09-01',
        dueDate: '2026-09-14',
        duration: 14,
        assignee: 'Sarah Jenkins',
        progress: 0,
        status: 'not_started',
        priority: 'high',
        level: 0,
        parentId: null,
        isMilestone: false,
        isSummary: true,
      },
      {
        id: 't-1-1',
        name: 'Stakeholder Interviews & Architecture Audit',
        wbs: '1.1',
        startDate: '2026-09-01',
        dueDate: '2026-09-05',
        duration: 5,
        assignee: 'Alex Rivera',
        progress: 0,
        status: 'not_started',
        priority: 'medium',
        level: 1,
        parentId: 't-1',
        isMilestone: false,
      },
      {
        id: 't-1-2',
        name: 'Security & Compliance Gap Analysis',
        wbs: '1.2',
        startDate: '2026-09-06',
        dueDate: '2026-09-11',
        duration: 6,
        assignee: 'Elena Rostova',
        progress: 0,
        status: 'not_started',
        priority: 'urgent',
        level: 1,
        parentId: 't-1',
        isMilestone: false,
      },
      {
        id: 't-1-3',
        name: 'Initiation Sign-off & Charter Approved',
        wbs: '1.3',
        startDate: '2026-09-14',
        dueDate: '2026-09-14',
        duration: 0,
        assignee: 'Sarah Jenkins',
        progress: 0,
        status: 'not_started',
        priority: 'high',
        level: 1,
        parentId: 't-1',
        isMilestone: true,
      },
      {
        id: 't-2',
        name: 'Phase 2: Target Cloud Foundation & Data Pipeline',
        wbs: '2',
        startDate: '2026-09-15',
        dueDate: '2026-10-04',
        duration: 20,
        assignee: 'Marcus Vance',
        progress: 0,
        status: 'not_started',
        priority: 'urgent',
        level: 0,
        parentId: null,
        isMilestone: false,
        isSummary: true,
      },
      {
        id: 't-2-1',
        name: 'VPC, IAM & Landing Zone Provisioning',
        wbs: '2.1',
        startDate: '2026-09-15',
        dueDate: '2026-09-21',
        duration: 7,
        assignee: 'Marcus Vance',
        progress: 0,
        status: 'not_started',
        priority: 'high',
        level: 1,
        parentId: 't-2',
        isMilestone: false,
      },
      {
        id: 't-2-2',
        name: 'Database Schema Extraction & ETL Scripts',
        wbs: '2.2',
        startDate: '2026-09-20',
        dueDate: '2026-09-30',
        duration: 11,
        assignee: 'Li Wei',
        progress: 0,
        status: 'not_started',
        priority: 'urgent',
        level: 1,
        parentId: 't-2',
        isMilestone: false,
      },
      {
        id: 't-2-3',
        name: 'Dry-Run Data Migration Milestone',
        wbs: '2.3',
        startDate: '2026-10-04',
        dueDate: '2026-10-04',
        duration: 0,
        assignee: 'Li Wei',
        progress: 0,
        status: 'not_started',
        priority: 'high',
        level: 1,
        parentId: 't-2',
        isMilestone: true,
      },
      {
        id: 't-legacy-spike',
        name: 'Legacy On-Premise Connector Spike (Descoped)',
        wbs: '2.4',
        startDate: '2026-09-25',
        dueDate: '2026-10-02',
        duration: 8,
        assignee: 'Elena Rostova',
        progress: 0,
        status: 'not_started',
        priority: 'low',
        level: 1,
        parentId: 't-2',
        isMilestone: false,
      },
      {
        id: 't-3',
        name: 'Phase 3: Service Cutover & UAT Validation',
        wbs: '3',
        startDate: '2026-10-05',
        dueDate: '2026-10-22',
        duration: 18,
        assignee: 'Sarah Jenkins',
        progress: 0,
        status: 'not_started',
        priority: 'medium',
        level: 0,
        parentId: null,
        isMilestone: false,
        isSummary: true,
      },
      {
        id: 't-3-1',
        name: 'Business User Acceptance Testing (UAT)',
        wbs: '3.1',
        startDate: '2026-10-05',
        dueDate: '2026-10-16',
        duration: 12,
        assignee: 'Alex Rivera',
        progress: 0,
        status: 'not_started',
        priority: 'high',
        level: 1,
        parentId: 't-3',
        isMilestone: false,
      },
      {
        id: 't-3-2',
        name: 'Production Cutover & Go-Live',
        wbs: '3.2',
        startDate: '2026-10-22',
        dueDate: '2026-10-22',
        duration: 0,
        assignee: 'Sarah Jenkins',
        progress: 0,
        status: 'not_started',
        priority: 'urgent',
        level: 1,
        parentId: 't-3',
        isMilestone: true,
      },
    ],
    summary: {
      totalTasks: 12,
      totalDuration: 64,
      startDate: '2026-09-01',
      dueDate: '2026-10-22',
      resources: [
        { name: 'Sarah Jenkins', taskCount: 4, totalDays: 32 },
        { name: 'Marcus Vance', taskCount: 2, totalDays: 27 },
        { name: 'Alex Rivera', taskCount: 2, totalDays: 17 },
        { name: 'Elena Rostova', taskCount: 2, totalDays: 14 },
        { name: 'Li Wei', taskCount: 2, totalDays: 11 },
      ],
    },
  },
  {
    id: 'bl-erp-v2',
    projectId: 'proj-erp-cloud',
    versionNumber: 2,
    name: 'Baseline 2: Mid-Q3 ETL Schedule Recalibration',
    description: 'Updated ETL sprint baseline adjusting for schema extraction complexity.',
    createdAt: '2026-09-10T14:30:00Z',
    createdBy: 'Sarah Jenkins, PMP',
    tasks: [
      {
        id: 't-1',
        name: 'Phase 1: Project Initiation & Assessment',
        wbs: '1',
        startDate: '2026-09-01',
        dueDate: '2026-09-14',
        duration: 14,
        assignee: 'Sarah Jenkins',
        progress: 100,
        status: 'completed',
        priority: 'high',
        level: 0,
        parentId: null,
        isMilestone: false,
        isSummary: true,
      },
      {
        id: 't-2',
        name: 'Phase 2: Target Cloud Foundation & Data Pipeline',
        wbs: '2',
        startDate: '2026-09-15',
        dueDate: '2026-10-06',
        duration: 22,
        assignee: 'Marcus Vance',
        progress: 20,
        status: 'in_progress',
        priority: 'urgent',
        level: 0,
        parentId: null,
        isMilestone: false,
        isSummary: true,
      },
    ],
    summary: {
      totalTasks: 11,
      totalDuration: 68,
      startDate: '2026-09-01',
      dueDate: '2026-10-24',
      resources: [
        { name: 'Sarah Jenkins', taskCount: 4, totalDays: 32 },
        { name: 'Marcus Vance', taskCount: 2, totalDays: 29 },
        { name: 'Alex Rivera', taskCount: 2, totalDays: 17 },
        { name: 'Li Wei', taskCount: 2, totalDays: 10 },
        { name: 'Elena Rostova', taskCount: 1, totalDays: 6 },
      ],
    },
  },
];

export const initialProjects: Project[] = [
  {
    id: 'proj-erp-cloud',
    name: 'Enterprise Cloud Transformation',
    description: 'Migration of core ERP infrastructure to cloud architecture with modern integrations.',
    startDate: '2026-09-01',
    status: 'active',
    manager: 'Sarah Jenkins, PMP',
    hasBaseline: true,
    baselineSavedAt: '2026-09-01T08:00:00Z',
    activeBaselineVersion: 1,
    baselineVersions: initialBaselineVersionsErp,
    createdDate: '2026-08-25',
  },
  {
    id: 'proj-mobile-app',
    name: 'Mobile App Experience 3.0',
    description: 'Next-generation mobile app revamp for iOS and Android with unified design system.',
    startDate: '2026-09-15',
    status: 'planning',
    manager: 'David Chen',
    hasBaseline: false,
    activeBaselineVersion: undefined,
    baselineVersions: [],
    createdDate: '2026-09-05',
  },
];

export const initialCustomColumns: CustomColumn[] = [
  {
    id: 'col-cost',
    projectId: 'proj-erp-cloud',
    name: 'Cost ($)',
    type: 'currency',
    defaultValue: 0,
  },
  {
    id: 'col-risk',
    projectId: 'proj-erp-cloud',
    name: 'Risk Level',
    type: 'select',
    options: ['Low', 'Medium', 'High', 'Critical'],
    defaultValue: 'Low',
  },
  {
    id: 'col-vendor',
    projectId: 'proj-erp-cloud',
    name: 'Vendor',
    type: 'text',
    defaultValue: 'Internal',
  },
  {
    id: 'col-deliverable',
    projectId: 'proj-erp-cloud',
    name: 'Client Sign-off',
    type: 'checkbox',
    defaultValue: false,
  },
];

const rawTasksErp: TaskItem[] = [
  // Phase 1
  {
    id: 't-1',
    projectId: 'proj-erp-cloud',
    wbs: '1',
    name: 'Phase 1: Project Initiation & Assessment',
    duration: 14,
    startDate: '2026-09-01',
    dueDate: '2026-09-14',
    progress: 100,
    status: 'completed',
    priority: 'high',
    assignee: 'Sarah Jenkins',
    dependencies: [],
    isMilestone: false,
    level: 0,
    parentId: null,
    baseline: { startDate: '2026-09-01', dueDate: '2026-09-14', duration: 14, savedAt: '2026-09-01', version: 1, assignee: 'Sarah Jenkins' },
    notes: 'Overall scoping and enterprise stakeholder interviews completed.',
    customFields: { 'col-cost': 45000, 'col-risk': 'Medium', 'col-vendor': 'McKinsey', 'col-deliverable': true },
  },
  {
    id: 't-1-1',
    projectId: 'proj-erp-cloud',
    wbs: '1.1',
    name: 'Stakeholder Interviews & Architecture Audit',
    duration: 5,
    startDate: '2026-09-01',
    dueDate: '2026-09-05',
    progress: 100,
    status: 'completed',
    priority: 'medium',
    assignee: 'Alex Rivera',
    dependencies: [],
    isMilestone: false,
    level: 1,
    parentId: 't-1',
    baseline: { startDate: '2026-09-01', dueDate: '2026-09-05', duration: 5, savedAt: '2026-09-01', version: 1, assignee: 'Alex Rivera' },
    customFields: { 'col-cost': 15000, 'col-risk': 'Low', 'col-vendor': 'Internal', 'col-deliverable': true },
  },
  {
    id: 't-1-2',
    projectId: 'proj-erp-cloud',
    wbs: '1.2',
    name: 'Security & Compliance Gap Analysis',
    duration: 6,
    startDate: '2026-09-06',
    dueDate: '2026-09-11',
    progress: 100,
    status: 'completed',
    priority: 'urgent',
    assignee: 'Elena Rostova',
    dependencies: ['t-1-1'],
    isMilestone: false,
    level: 1,
    parentId: 't-1',
    baseline: { startDate: '2026-09-06', dueDate: '2026-09-11', duration: 6, savedAt: '2026-09-01', version: 1, assignee: 'Elena Rostova' },
    customFields: { 'col-cost': 22000, 'col-risk': 'High', 'col-vendor': 'CyberSec Partners', 'col-deliverable': true },
  },
  {
    id: 't-1-3',
    projectId: 'proj-erp-cloud',
    wbs: '1.3',
    name: 'Initiation Sign-off & Charter Approved',
    duration: 0,
    startDate: '2026-09-14',
    dueDate: '2026-09-14',
    progress: 100,
    status: 'completed',
    priority: 'high',
    assignee: 'Sarah Jenkins',
    dependencies: ['t-1-2'],
    isMilestone: true,
    level: 1,
    parentId: 't-1',
    baseline: { startDate: '2026-09-14', dueDate: '2026-09-14', duration: 0, savedAt: '2026-09-01', version: 1, assignee: 'Sarah Jenkins' },
    customFields: { 'col-cost': 0, 'col-risk': 'Low', 'col-vendor': 'Executive Board', 'col-deliverable': true },
  },

  // Phase 2
  {
    id: 't-2',
    projectId: 'proj-erp-cloud',
    wbs: '2',
    name: 'Phase 2: Target Cloud Foundation & Data Pipeline',
    duration: 22,
    startDate: '2026-09-15',
    dueDate: '2026-10-06',
    progress: 45,
    status: 'in_progress',
    priority: 'urgent',
    assignee: 'Marcus Vance',
    dependencies: ['t-1-3'],
    isMilestone: false,
    level: 0,
    parentId: null,
    baseline: { startDate: '2026-09-15', dueDate: '2026-10-04', duration: 20, savedAt: '2026-09-01', version: 1, assignee: 'Marcus Vance' },
    customFields: { 'col-cost': 95000, 'col-risk': 'High', 'col-vendor': 'Google Cloud', 'col-deliverable': false },
  },
  {
    id: 't-2-1',
    projectId: 'proj-erp-cloud',
    wbs: '2.1',
    name: 'VPC, IAM & Landing Zone Provisioning',
    duration: 7,
    startDate: '2026-09-15',
    dueDate: '2026-09-21',
    progress: 90,
    status: 'in_progress',
    priority: 'high',
    assignee: 'Marcus Vance',
    dependencies: ['t-1-3'],
    isMilestone: false,
    level: 1,
    parentId: 't-2',
    baseline: { startDate: '2026-09-15', dueDate: '2026-09-21', duration: 7, savedAt: '2026-09-01', version: 1, assignee: 'Marcus Vance' },
    customFields: { 'col-cost': 30000, 'col-risk': 'Medium', 'col-vendor': 'Internal', 'col-deliverable': true },
  },
  {
    id: 't-2-2',
    projectId: 'proj-erp-cloud',
    wbs: '2.2',
    name: 'Database Schema Extraction & ETL Scripts',
    duration: 10,
    startDate: '2026-09-22',
    dueDate: '2026-10-01',
    progress: 30,
    status: 'in_progress',
    priority: 'urgent',
    assignee: 'Li Wei',
    dependencies: ['t-2-1'],
    isMilestone: false,
    level: 1,
    parentId: 't-2',
    baseline: { startDate: '2026-09-20', dueDate: '2026-09-30', duration: 11, savedAt: '2026-09-01', version: 1, assignee: 'Li Wei' },
    customFields: { 'col-cost': 40000, 'col-risk': 'High', 'col-vendor': 'DataTech Systems', 'col-deliverable': false },
  },
  {
    id: 't-2-3',
    projectId: 'proj-erp-cloud',
    wbs: '2.3',
    name: 'Dry-Run Data Migration Milestone',
    duration: 0,
    startDate: '2026-10-06',
    dueDate: '2026-10-06',
    progress: 0,
    status: 'not_started',
    priority: 'high',
    assignee: 'Li Wei',
    dependencies: ['t-2-2'],
    isMilestone: true,
    level: 1,
    parentId: 't-2',
    baseline: { startDate: '2026-10-04', dueDate: '2026-10-04', duration: 0, savedAt: '2026-09-01', version: 1, assignee: 'Li Wei' },
    customFields: { 'col-cost': 0, 'col-risk': 'Critical', 'col-vendor': 'Internal', 'col-deliverable': true },
  },
  // Scope Added Task (Created after Baseline 1 was signed off)
  {
    id: 't-2-4',
    projectId: 'proj-erp-cloud',
    wbs: '2.4',
    name: 'Automated Reconciliation & Audit Pipeline',
    duration: 6,
    startDate: '2026-10-01',
    dueDate: '2026-10-06',
    progress: 10,
    status: 'in_progress',
    priority: 'medium',
    assignee: 'Elena Rostova',
    dependencies: ['t-2-2'],
    isMilestone: false,
    level: 1,
    parentId: 't-2',
    baseline: null, // Scope Addition
    customFields: { 'col-cost': 18000, 'col-risk': 'Medium', 'col-vendor': 'Internal', 'col-deliverable': false },
  },

  // Phase 3
  {
    id: 't-3',
    projectId: 'proj-erp-cloud',
    wbs: '3',
    name: 'Phase 3: Service Cutover & UAT Validation',
    duration: 18,
    startDate: '2026-10-07',
    dueDate: '2026-10-24',
    progress: 0,
    status: 'not_started',
    priority: 'medium',
    assignee: 'Sarah Jenkins',
    dependencies: ['t-2-3'],
    isMilestone: false,
    level: 0,
    parentId: null,
    baseline: { startDate: '2026-10-05', dueDate: '2026-10-22', duration: 18, savedAt: '2026-09-01', version: 1, assignee: 'Sarah Jenkins' },
    customFields: { 'col-cost': 60000, 'col-risk': 'Medium', 'col-vendor': 'QA Labs', 'col-deliverable': false },
  },
  {
    id: 't-3-1',
    projectId: 'proj-erp-cloud',
    wbs: '3.1',
    name: 'Business User Acceptance Testing (UAT)',
    duration: 12,
    startDate: '2026-10-07',
    dueDate: '2026-10-18',
    progress: 0,
    status: 'not_started',
    priority: 'high',
    assignee: 'Alex Rivera',
    dependencies: ['t-2-3'],
    isMilestone: false,
    level: 1,
    parentId: 't-3',
    baseline: { startDate: '2026-10-05', dueDate: '2026-10-16', duration: 12, savedAt: '2026-09-01', version: 1, assignee: 'Alex Rivera' },
    customFields: { 'col-cost': 25000, 'col-risk': 'Medium', 'col-vendor': 'Internal', 'col-deliverable': true },
  },
  {
    id: 't-3-2',
    projectId: 'proj-erp-cloud',
    wbs: '3.2',
    name: 'Production Cutover & Go-Live',
    duration: 0,
    startDate: '2026-10-24',
    dueDate: '2026-10-24',
    progress: 0,
    status: 'not_started',
    priority: 'urgent',
    assignee: 'Sarah Jenkins',
    dependencies: ['t-3-1'],
    isMilestone: true,
    level: 1,
    parentId: 't-3',
    baseline: { startDate: '2026-10-22', dueDate: '2026-10-22', duration: 0, savedAt: '2026-09-01', version: 1, assignee: 'Sarah Jenkins' },
    customFields: { 'col-cost': 35000, 'col-risk': 'Critical', 'col-vendor': 'Google Cloud', 'col-deliverable': true },
  },
];

export const initialTasks: TaskItem[] = rollupSummaryTasks(recalculateWbsCodes(rawTasksErp));
